### PR TITLE
chore: update packages.json 

### PR DESCRIPTION
**Pull request by ashnamehrotra**
**What this PR does / why we need it**:
Update packages.json with yarn upgrade --latest

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ashnamehrotra** [comment]
had to temporarily change onBrokenLinks to warn, this issue is related https://github.com/facebook/docusaurus/issues/9758

**Comment by sozercan** [comment]
looks like there are a few broken links: https://github.com/eraser-dev/eraser/actions/runs/7575839168/job/20633351362?pr=956

opened https://github.com/eraser-dev/eraser/issues/958

**Review by sozercan — APPROVED** [review]
LGTM

**Comment by ashnamehrotra** [comment]
> looks like there are a few broken links: https://github.com/eraser-dev/eraser/actions/runs/7575839168/job/20633351362?pr=956
> 
> opened #958

I think the broken links are due to the docusaurus issue linked above, since the links have been fine before the upgrade. Is this still good to merge?

**Pull request merged**
