### PR TITLE
[BUG] Updating the wrong defaults in helm chart docs

### LINKED ISSUE #1032: [BUG] wrong defaults in the helm chart docs
### Version of Eraser

n/a

### Expected Behavior

```
runtimeConfig.components.collector | Settings for the collector component. | { enabled: true }
-- | -- | --
runtimeConfig.components.scanner | Settings for the scanner component. | { enabled: true }
```

https://github.com/eraser-dev/eraser/blob/main/charts/eraser/values.yaml#L39-L50

since this is generated actual change needs to be in: https://github.com/eraser-dev/eraser/blob/main/third_party/open-policy-agent/gatekeeper/helmify/static/README.md

### Actual Behavior

helm chart docs have the wrong defaults for collector and scanner. we should also check if anything else has the wrong defaults
https://github.com/eraser-dev/eraser/blob/main/charts/eraser/values.yaml#L39-L50

```
runtimeConfig.components.collector | Settings for the collector component. | { enabled: false }
-- | -- | --
runtimeConfig.components.scanner | Settings for the scanner component. | { enabled: false }
```

### Steps To Reproduce

_No response_

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

### PR DESCRIPTION
**Pull request by akhilsaivenkata**
**What this PR does / why we need it**: Updating the wrong defaults in helm chart docs

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #1032 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sozercan** [comment]
@akhilsaivenkata can you run `make manifests` and commit the changes too please? this is going to generate the `values.yaml` in `manifest_staging`. thanks!

**Comment by akhilsaivenkata** [comment]
> @akhilsaivenkata can you run `make manifests` and commit the changes too please? this is going to generate the `values.yaml` in `manifest_staging`. thanks!

Sure @sozercan . I will do that and commit those changes.

**Comment by akhilsaivenkata** [comment]
> @akhilsaivenkata can you run `make manifests` and commit the changes too please? this is going to generate the `values.yaml` in `manifest_staging`. thanks!

@sozercan , I ran make manifests command and it has made changes to Readme.md in manifests_staging but it did not make any changes to values.yaml in manifests_staging, but I can see values.yaml in manifests_staging has already has our required changes.

I have pushed the new changes of Readme.md in manifests_staging. Is there anything I am missing here?

**Comment by sozercan** [comment]
@akhilsaivenkata all good, this is my bad. i meant readme here

**Review by sozercan — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
