### PR TITLE
feat: automate release

### LINKED ISSUE #147: automate release action
**Describe the solution you'd like**
automate release process using gh actions

example: https://github.com/open-policy-agent/gatekeeper/blob/master/.github/workflows/release-pr.yaml

### PR DESCRIPTION
**Pull request by ashnamehrotra**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #147 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sozercan** [comment]
@ashnamehrotra did you validate this on your fork? if so, can you post an example action run, please?

**Comment by ashnamehrotra** [comment]
@sozercan yup! this was the example pr https://github.com/ashnamehrotra/eraser/pull/66 created by this action https://github.com/ashnamehrotra/eraser/actions/runs/3705867149

**Review by sozercan — APPROVED** [review]
LGTM

**Comment by sozercan** [comment]
@ashnamehrotra can you add the corresponding release docs also please? these can be a follow-up pr

**Pull request merged**
