### PR TITLE
docs: add Eraser logo to repo

### PR DESCRIPTION
**Pull request by karenhchu**
Addition of an Eraser logo to the project for project brand identity.

### CODE REVIEW

**Comment by karenhchu** [comment]
CC: @salaxander

**Comment by karenhchu** [comment]
@salaxander -- I updated my commit message to start with "docs: " per your suggestion and am still not passing the Semantic PR check. Any idea what other issues are holding it up?

**Comment by pmengelbert** [comment]
@karenhchu There were merge conflicts and it needed to be rebased. I can review and approve once the checks pass

**Comment by pmengelbert** [comment]
@karenhchu I misunderstood your question.  You need to edit the PR title (using the github UI), not the commit message, in order to pass the semantic check

**Comment by karenhchu** [comment]
@pmengelbert -- done, thank you!

**Comment by pmengelbert** [comment]
@karenhchu The svg looks like this in my browser. The font seems wrong there, and the text doesn't fit inside the eraser: 

strange font

**Comment by sozercan** [comment]
closing as logo is added in #855

**Pull request closed without merging**
