### PR TITLE
update client

### PR DESCRIPTION
**Pull request by sozercan**
Signed-off-by: Sertac Ozercan <sozercan@gmail.com>

**What this PR does / why we need it**:
Updates client in manager to use controller-runtime client instead of restclient

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cpuguy83** [comment]
This is going to make rebasing #88 difficult, I think.

**Comment by sozercan** [comment]
@cpuguy83 do you want to wait for #88 to be merged? we can rebase this after?

**Comment by sozercan** [comment]
@cpuguy83 rebased now

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
