### PR TITLE
chore: Prepare v1.0.0 release

### PR DESCRIPTION
**Pull request by ashnamehrotra**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sozercan** [comment]
@ashnamehrotra  can we use the github action for this?

**Comment by ashnamehrotra** [comment]
@sozercan it would create another release branch https://github.com/Azure/eraser/branches would we delete that one?

**Comment by sozercan** [comment]
opened #642 for tracking release pr block

i think this pr needs to target release-1.0 branch

**Comment by ashnamehrotra** [comment]
closing for #643 (pr to target release-1.0 branch)

**Pull request closed without merging**
